Fiap.Projeto.Web.MVC/Controllers/PerguntaController.cs
using Fiap.Projeto.Dominio.Models;
using Fiap.Projeto.Persistencia.UnitsOfWork;
using Fiap.Projeto.Web.MVC.Models;
using Fiap.Projeto.Web.MVC.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Web.Mvc;

namespace Fiap.Projeto.Web.MVC.Controllers
{
    [Authorize]
    public class PerguntaController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();
        
        #region Get
        [HttpGet]
        public ActionResult Cadastrar()
        {
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindByNameAsync(User.Identity.Name).Result;
            
            var perguntaViewModel = new PerguntaViewModel()
            {
                AlunoRm = user.Rm,
                NomeAluno = user.UserName 
            };

            return View(perguntaViewModel);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var perguntaViewModel = new PerguntaViewModel()
            {
                Perguntas = _unit.PerguntaRepository.Listar()
            };
            return View(perguntaViewModel);
        }

        public ActionResult Alterar(int perguntaId)
        {
            var pergunta = _unit.PerguntaRepository.BuscarPorId(perguntaId);
            var autor = _unit.AlunoRepository.BuscarPorId(pergunta.AlunoRm);

            var viewModel = new PerguntaViewModel()
            {
                AlunoRm = pergunta.AlunoRm,
                Titulo = pergunta.Titulo,
                Descricao = pergunta.Descricao,
                Data = pergunta.Data,
                Tag = pergunta.Tag,
                NomeAluno = autor.Nome
            };

            return View(viewModel);
        }
        #endregion

        #region Post
        [HttpPost]
        public ActionResult Cadastrar(PerguntaViewModel perguntaViewModel)
        {
            if (ModelState.IsValid)
            {
                var pergunta = new Pergunta()
                {
                    AlunoRm = perguntaViewModel.AlunoRm,
                    Titulo = perguntaViewModel.Titulo,
                    Descricao = perguntaViewModel.Descricao,
                    Data = DateTime.Now,
                    Tag = perguntaViewModel.Tag
                };

                _unit.PerguntaRepository.Cadastrar(pergunta);
                _unit.Salvar();

                return RedirectToAction("Listar");
            }
            else
            {
                return View(perguntaViewModel);
            }
        }

        [HttpPost]
        public ActionResult Alterar(Pergunta pergForm)
        {
            return RedirectToAction("Listar");
        }
        #endregion

        #region Dispose
        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

Fiap.Projeto.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/my-style.css" rel="stylesheet" />
    <title>OverflowedStack | @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP Connect", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", id="idLogo" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Feed de perguntas", "Listar", "Pergunta")</li>
                    <li>@Html.ActionLink("Pergunte você mesmo!", "Cadastrar", "Pergunta")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year FIAP - Todos os direitos reservados.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>